name: QMake Build Matrix

on: [push]

env:
  QT_VERSION: 5.14.0

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows Latest x64", artifact: "Windows-x64.zip",
            os: windows-latest,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:

    # Clone / Checkout
    - name: Clone / Checkout
      uses: actions/checkout@v2

    - name: Fetch history and tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* && git fetch --prune --unshallow

    # Create version file
    - name: Generate version file
      shell: bash
      run: ./version.sh

    # Download Qt
    - name: Download Qt
      id: qt
      shell: python
      run: |
        import urllib.request
        import re
        import os
        import fileinput
        import subprocess
        from pathlib import *
        
        qt_version = os.environ["QT_VERSION"]
        qt_version_dotless = qt_version.replace(".", "")
        url_os = "windows_x86"
        qt_package_name = "qt.qt5." + qt_version_dotless + ".win64_msvc2017_64"
        qt_dir_prefix = qt_version + "/msvc2017_64"
        qt_base_url = "https://download.qt.io/online/qtsdkrepository/" + url_os + "/desktop/qt5_" + qt_version_dotless

        response = urllib.request.urlopen(qt_base_url + "/Updates.xml")
        data = response.read()
        text = data.decode('utf-8')

        reg = "<Name>" + qt_package_name + "</Name>[\s\S]*<Version>([0-9+-.]+)</Version>[\s\S]*<DownloadableArchives>[\s\S]*qtbase([a-zA-Z0-9_-]+).7z"
        
        x=re.search(reg , text)
        if x:
          package_version = x.group(1)
          package_suffix = x.group(2)
          package_suffix = package_suffix.replace("-debug-symbols", "")
        else:
          print("Error with the regex.")

        os.mkdir("qt5")

        qt_dir = str(PurePath(os.environ["GITHUB_WORKSPACE"] + "/qt5/" + qt_dir_prefix))
        print(qt_dir)
        print("::set-output name=qt_dir::" + qt_dir)

        packages = ['qtbase', 'qtdeclarative', 'qttools', 'qtsvg', 'qtserialport']
        for package in packages:
          response = urllib.request.urlopen(qt_base_url + "/" + qt_package_name + "/" + package_version + package + package_suffix + ".7z")
          with open("./" +  package + ".7z", 'wb') as f:
            f.write(response.read())
          # Use cmake environment in order tar to be able t extract 7z file, I don't really know why the default 'tar' can't extract it...
          un7z_cmd = "cd qt5 && cmake -E tar xvf ../" + package + ".7z"
          status = subprocess.run(un7z_cmd, shell=True)
          if status.returncode != 0:
            print("Can't extract " + package + ".7z.")
        
        with fileinput.FileInput("qt5/" + qt_dir_prefix + "/mkspecs/qconfig.pri", inplace=True, backup='.bak') as file:
          for line in file:
            print(line.replace("Enterprise", "OpenSource"), end='')
            print(line.replace("licheck.exe", ""), end='')
            print(line.replace("licheck64", ""), end='')
            print(line.replace("licheck_mac", ""), end='')

    # PWD
    - name: Display qt_dir content
      shell: bash
      run: pwd
    
    # LS .
    - name: LS .
      shell: bash
      run: ls -larth

    # LS qt_dir
    - name: LS qt_dir
      shell: bash
      run: ls -larth qt5/5.14.0/msvc2017_64

    # Run QMake
    - name: Configure
      shell: python
      run: |
        # Import modules
        import subprocess
        import re
        import os

        # Prepare environment
        status = subprocess.run('"${{ matrix.config.environment_script }}" && set', shell=True, capture_output=True, text=True)
        if status.returncode != 0:
          print("Can't run environment script.")

        env_variables = status.stdout.splitlines()
        for variable in env_variables:
          print(variable)
          x=re.search("^([a-zA-Z0-9_-]+)=(.*)$", variable)
          if x:
            print("Set environment variable.")
            os.environ[x.group(1)] = x.group(2)
          else:
            print("no match.")
               
        # Run QMake
        status = subprocess.run(["${{ steps.qt.outputs.qt_dir }}/bin/qmake", "CONFIG+=release"], shell=True, capture_output=True)
        print(status)
        if status.returncode != 0:
          print("An error occurred with qmake")

    # Run Make
    - name: Build
      shell: python
      run: |
        import os
        import subprocess
        status = subprocess.run('"${{ matrix.config.environment_script }}" && nmake', shell=True)
        if status.returncode != 0:
          print("An error occurred with nmake")

    # Copy executable into deployment directory
    - name: Copy binary into deploy directory
      shell: python
      run: |
        import os
        import shutil
        os.mkdir("deploy")
        shutil.copyfile("release/SeriaLink.exe", "deploy/SeriaLink.exe")

    # Call Windeployqt to add dll etc.
    - name: Deploy
      shell: python
      run: |
        import subprocess
        status = subprocess.run(["${{ steps.qt.outputs.qt_dir }}/bin/windeployqt", "deploy"])
        if status.returncode != 0:
          print("An error occurred with windeployqt")
    
    # Create zip and upload deployment zip as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      id: upload_artifact
      with:
        path: deploy
        name: test