name: QMake Build Matrix

on: [push]

env:
  QT_VERSION: 5.14.0

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows Latest x64", artifact: "Windows-x64.zip",
            os: windows-latest,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:

    # Clone / Checkout
    - name: Clone / Checkout
      uses: actions/checkout@v2

    - name: Fetch history and tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* && git fetch --prune --unshallow

    # Create version file
    - name: Generate version file
      shell: bash
      run: ./version.sh

    # Download Qt
    - name: Download Qt
      id: qt
      shell: cmake -P {0}
      run: |
        set(qt_version $ENV{QT_VERSION})
        string(REPLACE "." "" qt_version_dotless "${qt_version}")
        if ("${{ runner.os }}" STREQUAL "Windows")
          set(url_os "windows_x86")
          if ("${{ matrix.config.environment_script }}" MATCHES "vcvars64.bat")
            set(qt_package_name "qt.qt5.${qt_version_dotless}.win64_msvc2017_64")
            set(qt_dir_prefix "${qt_version}/msvc2017_64")
          elseif ("${{ matrix.config.environment_script }}" MATCHES "vcvars32.bat")
            set(qt_package_name "qt.qt5.${qt_version_dotless}.win32_msvc2017")
            set(qt_dir_prefix "${qt_version}/msvc2017")
          else()
          endif()
        endif()
        set(qt_base_url "https://download.qt.io/online/qtsdkrepository/${url_os}/desktop/qt5_${qt_version_dotless}")
        file(DOWNLOAD "${qt_base_url}/Updates.xml" ./Updates.xml SHOW_PROGRESS)
        file(READ ./Updates.xml updates_xml)
        string(REGEX MATCH "<Name>${qt_package_name}.*<Version>([0-9+-.]+)</Version>.*<DownloadableArchives>qtbase([a-zA-Z0-9_-]+).7z" updates_xml_output "${updates_xml}")
        set(package_version ${CMAKE_MATCH_1})
        set(package_suffix ${CMAKE_MATCH_2})
        string(REPLACE "-debug-symbols" "" package_suffix "${package_suffix}")
        # Workaround for CMake's greedy regex
        if ("${{ matrix.config.environment_script }}" MATCHES "vcvars32.bat")
          string(REPLACE "X86_64" "X86" package_suffix "${package_suffix}")
        endif()
        file(MAKE_DIRECTORY qt5)
        # Save the path for other steps
        file(TO_CMAKE_PATH "$ENV{GITHUB_WORKSPACE}/qt5/${qt_dir_prefix}" qt_dir)
        message("::set-output name=qt_dir::${qt_dir}")
        foreach(package qtbase qtdeclarative qttools qtsvg qtserialport)
          file(DOWNLOAD
            "${qt_base_url}/${qt_package_name}/${package_version}${package}${package_suffix}.7z" ./${package}.7z
            SHOW_PROGRESS
          )
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ../${package}.7z WORKING_DIRECTORY qt5)
        endforeach()
        file(READ "qt5/${qt_dir_prefix}/mkspecs/qconfig.pri" qtconfig)
        string(REPLACE "Enterprise" "OpenSource" qtconfig "${qtconfig}")
        string(REPLACE "licheck.exe" "" qtconfig "${qtconfig}")
        string(REPLACE "licheck64" "" qtconfig "${qtconfig}")
        string(REPLACE "licheck_mac" "" qtconfig "${qtconfig}")
        file(WRITE "qt5/${qt_dir_prefix}/mkspecs/qconfig.pri" "${qtconfig}")

    # Run QMake
    - name: Configure
      shell: python
      run: |
        # Import modules
        import subprocess
               
        # Run QMake
        status = subprocess.run('"${{ matrix.config.environment_script }}" && "${{ steps.qt.outputs.qt_dir }}/bin/qmake CONFIG+=release"', shell=True)
        if status.returncode != 0:
          print("An error occurred with qmake")

    # Run Make
    - name: Build
      shell: python
      run: |
        import os
        import subprocess
        status = subprocess.run('"${{ matrix.config.environment_script }}" && nmake', shell=True)
        if status.returncode != 0:
          print("An error occurred with nmake")

    # Copy executable into deployment directory
    - name: Copy binary into deploy directory
      shell: python
      run: |
        import os
        import shutil
        os.mkdir("deploy")
        shutil.copyfile("release/SeriaLink.exe", "deploy/SeriaLink.exe")

    # Call Windeployqt to add dll etc.
    - name: Deploy
      shell: python
      run: |
        import subprocess
        status = subprocess.run(["${{ steps.qt.outputs.qt_dir }}/bin/windeployqt", "deploy"])
        if status.returncode != 0:
          print("An error occurred with windeployqt")
    
    # Create zip and upload deployment zip as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      id: upload_artifact
      with:
        path: deploy
        name: test